rvm: '2.2.2'

script:
  - mkdir -p spec && bundle exec rspec spec
  - mkdir -p features && bundle exec cucumber

before_install:
- sed -i '2d' Gemfile
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
  - psql -c 'create database chitter_test;' -U postgres
